# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "users",
        max_ram_gb=peewee.FloatField(default=4.0),
    )


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("users", ["max_ram_gb"])
